### ISSUE TITLE
404 on dark node log and setting pages

### ISSUE THREAD

**Issue by bachew** [republicprotocol/republic-go#11]
Dark node `/log` and `/settings` urls are not served by web server but only handled through js routing, directly accessing the urls result in `404 page not found`.

**Comment by loongy** [comment]
The web server handlers are started in the `StartUI` method in the `darknode` package. It should just be a matter of creating a catch all pattern, `/*`, _after_ the `/config`, and serving the website assets from this catch all.

**Comment by jazg** [comment]
This has been fixed and merged to `master`.
