### ISSUE TITLE
RenEx trades not going through

### ISSUE THREAD

**Issue by TheDon22** [republicprotocol/republic-go#64]
**Description**
buy orders set at above market price for 16 hours. 
had some one do a sell order at same price and no trade occur. they haven't been able to sell either.

Also one trade is stuck "executing" but no trade has occured.

here are two technically matched orders that went unfilled
UJaGP+p5hemxocwbedjXrGzKeBeabVEeg237TYX+PDY= my buy order 
ZhEgxs8PzAYvPwZ+5+MniM9fsQJ8+hDFykz01rcKAek= other friends' sell order same value and trade pair
**Expected Behavior**

**Steps to reproduce**

followed steps to buy test ETH on Kovan testnet. deposited ETH. made buy orders above market price.
other buy orders "open"
uZzpNs26PhGZKMUOjea9VHzoKY8KhYK2HFiMW++udiA=
CPvwr3JpioDOaXBNz7jKC1pUBEaVDgCb5MJTUK131WQ=
/FFU/ZN9Sw4kMmZG0WYoM7tx/LcGavRdMhwBNyZ6Aqc=

this order is stuck "executing"
3C3EH8driBlabMxfp9eMJsMe56iW0zbZ8l8XWklU6LU=

**Version**

RenEx trading terminal testnet
**Operating system**

macOSX high sierra 10.13.5

**Comment by loongy** [comment]
The secure matching engine logs show that the matches are in fact happening, but the network logs show that there is a communication issue between the Darknodes and Infura that is preventing them from correctly updating the status of orders in the orderbook contract.

**Comment by TheDon22** [comment]
thank you for update!

**Comment by loongy** [comment]
Fixed by https://github.com/republicprotocol/republic-go/pull/62. The respective deployment to F∅ is pending the merging of this PR.
